rule("csproj")
	set_extensions(".csproj")
	on_build_file(function (target, sourcefile)
		os.execv("dotnet", {"build", sourcefile, "-o", target:targetdir()})
	end)
    after_build(function(target)
        print("Copying resources...")
        local binaryPath = "$(buildir)/$(plat)/$(arch)/$(mode)"
        os.cp("Sample/DotNetLib.deps.json", binaryPath)
        os.cp("Sample/DotNetLib.runtimeconfig.json", binaryPath)
        print("Copying resources... Done !")
    end)

rule_end()

-- target("concerto-dotnet-tests")
--     set_kind("binary")
--     set_languages("cxx20")
--     set_warnings("all")
--     add_deps("concerto-dotnet")
--     add_packages("gtest")
--     add_files("*.cpp")
--     add_files("../Sample/DotNetLib.csproj")
--     add_rules("csproj")
